### ISSUE TITLE
What is the procedure for installation?

### ISSUE THREAD

**Issue by getuliovinicius** [faustocintra/vscode-longsight-light-theme#1]
**Hi teacher, how are you?**

I would like to know the procedure to follow to **install** this theme. For example, if this was Linux software, there should be an **Install** session in your [README.md](https://github.com/fgcintra/vscode-longsight-light-theme/blob/master/README.md) file with something similar to:

``` bash
$ sudo apt install software-name
``` 
As it is a theme for the _VSCode_, the session could bring a sequence of static **images** or **gifs** detailing the installation procedure.

**Comment by faustocintra** [comment]
Hi, Getulio!

As for every VSCode extension, just open the editor, click on the fourth button
on the left pane and search for the theme name. Once you've found it, just
click on install and reload VSCode window.

Regards,


fausto@fgcintra.pro.br | http://fgcintra.pro.br
Currículo Lattes: http://lattes.cnpq.br/5529456425773756

Faculdade de Tecnologia de Franca "Dr. Thomaz Novelino" - Fatec Franca

2018-03-18 13:01 GMT-03:00 Getulio Vinicius <notifications@github.com>:
